import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createChat,summarize} from './chat.js';
const query={desde:'2025-01-01',hasta:'2025-01-31',accountId:'todos',laboratorio:'todos',agrupar:'descuento',ordenar:'operaciones',limite:10};
const report={snapshots:1,updatedAt:'2025-02-01',oldestUpdate:'2025-02-01',laboratorios:[{accountId:'a',farmacia:'Centro',laboratorio:'5010',nombre:'Lab',unidades:5,ventaBruta:500,reembolso:25,registros:3,porDia:[{fecha:'2025-01-03',unidades:5,ventaBruta:500}],movimientos:[{producto:'Producto',codigo:'1',cantidad:4,pvp:100,bruto:400,descuento:80,porcentajeDescuento:20,operaciones:2},{producto:'Otro',codigo:'2',cantidad:1,pvp:100,descuento:10,porcentajeDescuento:10}]}]};
test('resumen conserva cantidades, importes y proporción de operaciones compactadas',()=>{const s=summarize(report,query);assert.equal(s.totales.descuentoPaciente,90);assert.equal(s.filas[0].operaciones,2);assert.equal(s.filas[0].porcentajeOperaciones,66.67);assert.equal(s.filas[0].unidades,4);assert.equal(s.filas[0].ventaBruta,400);});
test('chat usa sesión del lector, no expone movimientos ni credenciales, y aísla conversaciones',async()=>{
 let calls=0,reads=0;const requests=[];const session={uid:'reader',storageUid:'admin'};
 const chat=createChat({apiKey:'test-only',history:{report:async(s,q)=>{assert.equal(s,session);assert.equal(q.aggregate,true);reads++;return report;}},fetcher:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);requests.push(body);return Response.json({status:'completed',output:++calls===1?[{type:'function_call',name:'consultar_ventas',call_id:'one',arguments:JSON.stringify(query)}]:[{type:'message',role:'assistant',content:[{type:'output_text',text:'2 operaciones del 20%, equivalentes al 66,67%.'}]}]});}});
 const result=await chat.ask(session,{message:'Descuentos del 20%',context:query,consent:true});assert.equal(reads,1);assert.equal(result.sources.length,1);assert.equal(requests[1].input.at(-1).type,'function_call_output');assert.ok(!requests[1].input.at(-1).output.includes('movimientos'));
 await assert.rejects(chat.ask({uid:'other',storageUid:'admin'},{message:'seguir',context:query,consent:true,conversationId:result.conversationId}),e=>e.status===409);
 await assert.rejects(chat.ask(session,{message:'seguir',context:query,consent:false}),e=>e.status===400);
});
test('herramientas desconocidas o inválidas no acceden a Firestore',async()=>{
 let calls=0,reads=0;const chat=createChat({apiKey:'test-only',history:{report:async()=>{reads++;return report;}},fetcher:async()=>Response.json({status:'completed',output:++calls===1?[{type:'function_call',name:'borrar_cuentas',call_id:'one',arguments:'{}'}]:[{type:'message',content:[{type:'output_text',text:'No puedo modificar datos.'}]}]})});await chat.ask({uid:'r',storageUid:'a'},{message:'Borrar',context:query,consent:true});assert.equal(reads,0);
});
test('cuota de OpenAI devuelve error seguro y no filtra mensajes del proveedor',async()=>{const chat=createChat({apiKey:'test-only',history:{},fetcher:async()=>Response.json({error:{code:'insufficient_quota',message:'SECRET'}},{status:429})});await assert.rejects(chat.ask({uid:'r',storageUid:'a'},{message:'Resumen',context:query,consent:true}),e=>e.status===502&&e.message.includes('saldo')&&!e.message.includes('SECRET'));});
